# This is a basic workflow to help you get started with Actions

name: cs-pr-check

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  cs-pr-check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      contents: read

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: jsoref/check-spelling@prerelease
        with:
          debug: 1
          bucket: .github/actions
          project: spelling
          event_aliases: '{"workflow_dispatch":"schedule"}'
        env:
          timeframe: 600
